### PR TITLE
Changed coveralls workflow to run Python 3.5/3.6 on ubuntu-20.04

### PR DESCRIPTION
**Pull request by andy-maier**
Fixes issue #374 .
For details, see the commit message.

### CODE REVIEW

**Comment by andy-maier** [comment]
I created issue #376 for the tox failure on Python 3.6, but think that this PR successfully addresses the issue it intended to fix, namely to run Python 3.5 and 3.6 again, so I suggest to go forward with this PR and solve issue #376 separately.

**Comment by gliptak** [comment]
could 3.5/3.6 dropped from supported?

https://www.python.org/downloads/

**Comment by andy-maier** [comment]
> could 3.5/3.6 dropped from supported?

Not as far as our projects are concerned, because we urgently need a solution for #252 and it would be great if we could get that solution also for Python 3.5 and 3.6.

**Comment by TheKevJames** [comment]
Thanks for the contribution! However, Python 3.5 and 3.6 have been dropped as they are now end-of-life'd. Please see https://github.com/TheKevJames/coveralls-python/issues/393#issuecomment-2079551748 for more context.

**Pull request closed without merging**
